# Generated by Django 4.2.6 on 2023-12-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoRecisorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('data_de_nascimento', models.DateField()),
                ('admissao', models.DateField()),
                ('demissao', models.DateField()),
                ('salario_bruto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rescisao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aviso_previo_proporcional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('decimo_terceiro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ferias', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ferias_vencidas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('indenizacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fgts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dias_trabalhados_no_ano', models.IntegerField()),
                ('meses_trabalhados', models.IntegerField()),
                ('aviso_previo_indenizado', models.BooleanField(default=False)),
                ('motivo_rescisao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Provisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rubrica', models.CharField(blank=True, max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('subcategoria', models.CharField(blank=True, max_length=100)),
                ('detalhamento', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('data_de_nascimento', models.DateField()),
                ('tipo_logradouro', models.CharField(max_length=50)),
                ('nome_logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('projetos', models.ManyToManyField(blank=True, to='contabil.provisao')),
            ],
        ),
    ]
